/**
 * 版权所有(C) 2012 深圳市雁联计算系统有限公司
 * 创建:ZhangDM(Mingly) 2012-10-27
 */

package com.ylink.ylpay.common.project.pay.constant;

/**
 * @author ZhangDM(Mingly)
 * @date 2012-10-27
 * @description：业务步骤代码枚举类
 */

public enum StepKeyEnum {

	GATEWAY_RECHARGE_KEY("GATEWAY_RECHARGE", "网关充值步骤KEY"), SHORTCUT_RECHARGE_KEY(
			"SHORTCUT_RECHARGE", "快捷充值步骤KEY"),
			SHORTCUT_RECHARGE_EPAY_KEY(
					"SHORTCUT_RECHARGE_EPAY_KEY", "快捷充值步骤KEY"),OFFLINE_RECHARGE_KEY(
			"OFFLINE_RECHARGE", "线下充值步骤KEY"), 
			OFFLINE_RECHARGE_EPAY_KEY(
					"OFFLINE_RECHARGE_EPAY", "线下充值保证金KEY"),
					OFFLINE_RECHARGE_1_KEY(
			"OFFLINE_RECHARGE_1", "交易所充值-机构到交易所KEY"), ADDITIONAL_RECHARGE_KEY(
			"ADDITIONAL_RECHARGE", "补录步骤KEY"), ACCOUNT_TRANSFER_KEY(
			"ACCOUNT_TRANSFER", "账户转账步骤KEY"), PAYABLES_TRANSFER_KEY(
			"PAYABLES_TRANSFER", "应付款转账步骤KEY"),

	GUARANTEE_ACCOUNT_PAYMENT_KEY("GUARANTEE_ACCOUNT_PAYMENT", "账户担保支付步骤KEY"), GUARANTEE_GATEWAY_PAYMENT_RECHARGE_KEY(
			"GUARANTEE_GATEWAY_PAYMENT_RECHARGE", "网关担保支付-充值步骤KEY"), GUARANTEE_GATEWAY_PAYMENT_PAYMENT_KEY(
			"GUARANTEE_GATEWAY_PAYMENT_PAYMENT", "网关支付-支付步骤-KEY"), GUARANTEE_SHORTCUT_PAYMENT_RECHARGE_KEY(
			"GUARANTEE_SHORTCUT_PAYMENT_RECHARGE", "快捷担保支付-充值步骤KEY"), GUARANTEE_SHORTCUT_PAYMENT_PAYMENT_KEY(
			"GUARANTEE_SHORTCUT_PAYMENT_PAYMENT", "快捷担保支付-支付步骤KEY"), GUARANTEE_CONFIRM_KEY(
			"GUARANTEE_CONFIRM", "担保确认付款步骤KEY"), GUARANTEE_REFUSE_KEY(
			"GUARANTEE_REFUSE", "担保拒绝付款步骤KEY"),

	ACCOUNT_PAYMENT_KEY("ACCOUNT_PAYMENT", "账户支付步骤KEY"), GATEWAY_PAYMENT_RECHARGE_KEY(
			"GATEWAY_PAYMENT_RECHARGE", "网关支付-充值步骤KEY"), GATEWAY_PAYMENT_CR_RECHARGE_KEY(
			"GATEWAY_PAYMENT_CR_RECHARGE", "网关支付-信用卡充值步骤KEY"), GATEWAY_PAYMENT_RECHARGE_EPAY_KEY(
			"GATEWAY_PAYMENT_RECHARGE_EPAY", "网关支付-充值步骤-现金易-KEY"), GATEWAY_PAYMENT_PAYMENT_KEY(
			"GATEWAY_PAYMENT_PAYMENT", "网关支付-支付步骤KEY"), SHORTCUT_PAYMENT_RECHARGE_KEY(
			"SHORTCUT_PAYMENT_RECHARGE", "快捷支付-充值步骤KEY"),SHORTCUT_PAYMENT_RECHARGE_EPAY_KEY(
					"SHORTCUT_PAYMENT_EPAY_RECHARGE", "快捷支付-其他货币资金-充值步骤KEY"), SHORTCUT_PAYMENT_PAYMENT_KEY(
			"SHORTCUT_PAYMENT_PAYMENT", "快捷支付-支付步骤KEY"),

	WITHDRAW_APPLY_KEY("WITHDRAW_APPLY", "提现申请步骤KEY"), WITHDRAW_APPLY_1_KEY(
			"WITHDRAW_APPLY_1", "交易所提现-交易所到机构KEY"), WITHDRAW_REFUSE_KEY(
			"WITHDRAW_REFUSE", "提现拒绝步骤KEY"), WITHDRAW_REFUSE_1_KEY(
			"WITHDRAW_REFUSE_1", "交易所提现-拒绝-机构到交易所KEY"), WITHDRAW_CONFIRM_KEY(
			"WITHDRAW_CONFIRM", "提现确认步骤KEY"),
			WITHDRAW_CONFIRM_EPAY_KEY("WITHDRAW_CONFIRM_EPAY", "提现确认步骤KEY"),
			WITHDRAW_CONFIRM_OPPOSITE_KEY(
			"WITHDRAW_CONFIRM_OPPOSITE", "提现确认反向步骤KEY"),
			//银行到银行
			BANK_ACCOUNT_TRANSFER_KEY("BANK_ACCOUNT_TRANSFER", "银行账户转账步骤KEY"), 
			//银行到现金易
			BANK_TRANSFER_EPAY_KEY("BANK_TRANSFER_EPAY", "银行账户转账到EPAY转账步骤KEY"), 
			//现金易到银行
			EPAY_TRANSFER_BANK_KEY("EPAY_TRANSFER_BANK", "EPAY账户转账到银行步骤KEY"), 
			//现金易到现金易
			EPAY_TRANSFER_EPAY_KEY("EPAY_TRANSFER_EPAY", "EPAY账户转账步骤KEY"), 
			RECHARGE_ROLLBACK_APPLY_KEY(
			"RECHARGE_ROLLBACK_APPLY", "充值回退申请步骤KEY"), RECHARGE_ROLLBACK_REFUSE_KEY(
			"RECHARGE_ROLLBACK_REFUSE", "充值回退拒绝步骤KEY"), RECHARGE_ROLLBACK_CONFIRM_KEY(
			"RECHARGE_ROLLBACK_CONFIRM", "充值回退确认步骤KEY"), EPAY_PURCHASE_KEY(
			"EPAY_PURCHASE_KEY", "现金易申购步骤KEY"), EPAY_PAY_REDEEM1_KEY(
			"EPAY_PAY_REDEEM1_KEY", "现金易支付赎回步骤1KEY"), EPAY_PAY_REDEEM2_KEY(
			"EPAY_PAY_REDEEM2_KEY", "现金易支付赎回步骤2KEY"), EPAY_PAY_REDEEM3_KEY(
			"EPAY_PAY_REDEEM3_KEY", "现金易支付赎回步骤3KEY"), EPAY_PAY_PURCHASE1_KEY(
			"EPAY_PAY_PURCHASE1_KEY", "现金易支付申购步骤1KEY"), EPAY_PAY_PURCHASE2_KEY(
			"EPAY_PAY_PURCHASE2_KEY", "现金易支付申购步骤2KEY"), EPAY_PAY_PURCHASE3_KEY(
			"EPAY_PAY_PURCHASE3_KEY", "现金易支付申购步骤3KEY"), EPAY_PAY_PURCHASE4_KEY(
			"EPAY_PAY_PURCHASE4_KEY", "现金易支付申购步骤4KEY"), BANK_ACCOUNT_COLLECTION_KEY1(
			"BANK_ACCOUNT_COLLECTION_KEY1", "银行账户收账步骤KEY1"), BANK_ACCOUNT_COLLECTION_KEY2(
			"BANK_ACCOUNT_COLLECTION_KEY2", "银行账户收账步骤KEY2"), BANK_ACCOUNT_PAYMENT_KEY(
			"BANK_ACCOUNT_PAYMENT_KEY", "银行账户付账-支付步骤KEY"),

	// 实时赎回业务
	TIMMELY_REDEMPTION1_KEY("TIMMELY_REDEMPTION1_KEY", "实时赎回提现步骤1KEY"), TIMMELY_REDEMPTION2_KEY(
			"TIMMELY_REDEMPTION2_KEY", "实时赎回提现步骤2KEY"), TIMMELY_REDEMPTION3_KEY(
			"TIMMELY_REDEMPTION3_KEY", "实时赎回提现步骤3KEY"), TIMMELY_REDEMPTION4_KEY(
			"TIMMELY_REDEMPTION4_KEY", "实时赎回提现步骤4KEY"), TIMMELY_REDEMPTION5_KEY(
			"TIMMELY_REDEMPTION5_KEY", "实时赎回提现步骤5KEY"),
			
	//实时赎回资金调拨
	TIMELY_REDEMPTION_TRANSFER1_KEY("TIMELY_REDEMPTION_TRANSFER1_KEY", "实时赎回资金调拨步骤1KEY"),

	// 实时赎回到备付金
	/**
	 * 1: 借：备付金-基金-基金公司A 贷：其他应付款-基金-基金公司A赎回
	 * 
	 * 2:借：其他应付款-基金-基金公司A赎回 贷：备付金-基金-客户
	 * 
	 * 
	 */
	FUND_TIMELY_PAY_REDEMPTION_KEY1("FUND_TIMELY_PAY_REDEMPTION_KEY1",
			"基金支付赎回提现步骤1KEY"), 
	FUND_TIMELY_PAY_REDEMPTION_KEY2(
			"FUND_TIMELY_PAY_REDEMPTION_KEY2", "基金支付赎回提现步骤2KEY"),

	/**
	 * 3:借：备付金-基金-客户 贷：其他应付款-基金-基金公司B
	 */

	FUND_TIMELY_PAY_PURCHASE_KEY1("FUND_TIMELY_PAY_PURCHASE_KEY1",
			"基金支付申购步骤KEY"),
			
			/**
			 * 还款 划款 赔付、退款 （慧投使用）
			 */
			
	BASE_REPAYMENT_KEY1("BASE_REPAYMENT_KEY1","消费划款步骤key1"),	
	
	BASE_REPAYMENT_KEY2("BASE_REPAYMENT_KEY2","消费划款步骤key2"),	


	;

	private String value;
	private String displayName;

	public String getValue() {
		return value;
	}

	public String getDisplayName() {
		return displayName;
	}

	private StepKeyEnum(String value, String displayName) {
		this.value = value;
		this.displayName = displayName;
	}

	/**
	 * 支付-充值步骤，调账修改支付订单状态
	 */
	public static StepKeyEnum[] getPaymentRechargeKeys() {
		return new StepKeyEnum[] { GATEWAY_PAYMENT_RECHARGE_KEY,
				GATEWAY_PAYMENT_RECHARGE_EPAY_KEY,
				SHORTCUT_PAYMENT_RECHARGE_KEY };
	}

	/**
	 * 支付-支付步骤，调账仅支付订单冲正
	 */
	public static StepKeyEnum[] getPaymentPaymentKeys() {
		return new StepKeyEnum[] { ACCOUNT_PAYMENT_KEY,
				GATEWAY_PAYMENT_PAYMENT_KEY, SHORTCUT_PAYMENT_PAYMENT_KEY };
	}

	/**
	 * 支付步骤，调账修改支付和交易订单状态
	 */
	public static StepKeyEnum[] getPaymentAccountKeys() {
		return new StepKeyEnum[] { BANK_ACCOUNT_COLLECTION_KEY1,
				BANK_ACCOUNT_COLLECTION_KEY2, ACCOUNT_TRANSFER_KEY,
				PAYABLES_TRANSFER_KEY };
	}
}
